import React from 'react';
import LinkBox from "../../../elements/LinkBox.jsx";

export default function SoftwareArchitecture() {
    return (
        <div className="main-content">
            <section className={"semesterframe"}>
                <h1>Software Architecture</h1>
                <div className="semester-linkbox-container">
                    <LinkBox text="Lecture 1" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%201%20-%20SA.pptx?d=wc23d43b659cc4becb595fc6702857471&csf=1&web=1&e=a0VDqS"}/>
                    <LinkBox text="Lecture 2" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%202%20-%20SA.pptx?d=w61c6d4928b8a49308139be261a64aa7d&csf=1&web=1&e=JpyiSJ"}/>
                    <LinkBox text="Lecture 3" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%203%20-%20SA%20.pptx?d=w82337ddb11704bd380496f0463f540b5&csf=1&web=1&e=orxaD2"}/>
                    <LinkBox text="Lecture 4" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%204%20-%20SA.pptx?d=w5aabc12f239c4d298bb36794066e7126&csf=1&web=1&e=MlbOy9"}/>
                    <LinkBox text="Lecture 5" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%205%20-%20SA.pptx?d=w5409381c9fdc4000bdbfb21427d0a772&csf=1&web=1&e=HAEFaC"}/>
                    <LinkBox text="Lecture 6" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%206%20-%20SA.pptx?d=wb8e96278411c4514b2df07dc9ad2d66e&csf=1&web=1&e=wYijPB"}/>
                    <LinkBox text="Lecture 7" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%207%20-%20SA.pptx?d=w34ecd1e9c0bd4a7b8a46b05cade90ee4&csf=1&web=1&e=uRxCRa"}/>
                    <LinkBox text="Lecture 8" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%208%20-%20SA.pptx?d=w68a98ee0695e4380ab5c8975ae2e0b73&csf=1&web=1&e=lPiNAw"}/>
                    <LinkBox text="Lecture 9" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%209%20-%20SA.pptx?d=w51a3e1a7d6f64f14a215a4b046f64648&csf=1&web=1&e=7MR01s"}/>
                    <LinkBox text="Lecture 10" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%2010%20-%20SA.pptx?d=w15ac4dedadaf42e1bef33b4aa5ae2045&csf=1&web=1&e=rcTKDr"}/>
                    <LinkBox text="Lecture 11" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white" href={"https://syddanskuni-my.sharepoint.com/:p:/r/personal/vimis22_student_sdu_dk/Documents/Syddansk%20Universitets%20Mappe/6.%20Semester/SA/Noter%20i%20SA/Vivek%20Noter%20til%20Software%20Arkitektur%2011%20-%20SA.pptx?d=w2524e3e8fbbe4c3585232cb4a17525c6&csf=1&web=1&e=0rASZw"}/>
                    <LinkBox text="Lecture 12 (No Notes)" textsize="16px" textcolor="black" textHeight="auto" textWidth="auto" textBorder="none" textBorderWeight="1px" containerHeight="auto" containerWidth="auto" containerBorder="none" containerBorderWeight="1px" backgroundColor="white"/>
                </div>
            </section>
        </div>
    )
}